import GameController

extension GCController: @retroactive Identifiable {}
extension GCKeyCode: @retroactive Codable {}

extension GCController {
    var symbol: String {
        switch self.productCategory {
        case GCProductCategoryXboxOne:
            "xbox.logo"
        case GCProductCategoryDualSense, GCProductCategoryDualShock4:
            "playstation.logo"
        default:
            "gamecontroller"
        }
    }

    var batterySymbol: String {
        guard let battery else { return "cable.connector" }
        return switch battery.batteryState {
        case .unknown:        "battery.0percent"
        case .full:           "battery.100percent"
        case .discharging: switch battery.batteryLevel {
            case 0:           "battery.0percent"
            case 0.00...0.25: "battery.25percent"
            case 0.25...0.50: "battery.50percent"
            case 0.50...0.75: "battery.75percent"
            case 0.75...1.00: "battery.100percent"
            default:          "battery.0percent"
            }
        case .charging: switch battery.batteryLevel {
        case 0:           "battery.0percent.bolt"
        case 0.00...0.25: "battery.25percent.bolt"
        case 0.25...0.50: "battery.50percent.bolt"
        case 0.50...0.75: "battery.75percent.bolt"
        case 0.75...1.00: "battery.100percent.bolt"
        default:          "battery.0percent.bolt"
        }
        @unknown default: "battery.0percent.bolt"
        }
    }
}

// MARK: Keyboard display names

extension GCKeyCode {
    // FIXME: Localize... is it possible to obtain the keyboard layout information?
    var displayName: String {
        return switch self {
        case .keyA: "A Key"
        case .keyB: "B Key"
        case .keyC: "C Key"
        case .keyD: "D Key"
        case .keyE: "E Key"
        case .keyF: "F Key"
        case .keyG: "G Key"
        case .keyH: "H Key"
        case .keyI: "I Key"
        case .keyJ: "J Key"
        case .keyK: "K Key"
        case .keyL: "L Key"
        case .keyM: "M Key"
        case .keyN: "N Key"
        case .keyO: "O Key"
        case .keyP: "P Key"
        case .keyQ: "Q Key"
        case .keyR: "R Key"
        case .keyS: "S Key"
        case .keyT: "T Key"
        case .keyU: "U Key"
        case .keyV: "V Key"
        case .keyW: "W Key"
        case .keyX: "X Key"
        case .keyY: "Y Key"
        case .keyZ: "Z Key"
        case .one: "1 Key"
        case .two: "2 Key"
        case .three: "3 Key"
        case .four: "4 Key"
        case .five: "5 Key"
        case .six: "6 Key"
        case .seven: "7 Key"
        case .eight: "8 Key"
        case .nine: "9 Key"
        case .zero: "0 Key"
        case .returnOrEnter: "Enter"
        case .escape: "Escape"
        case .deleteOrBackspace: "Backspace"
        case .tab: "Tab"
        case .spacebar: "Space"
        case .hyphen: "- Key"
        case .equalSign: "= Key"
        case .openBracket: "[ Key"
        case .closeBracket: "] Key"
        case .backslash: "\\ Key"
        case .nonUSPound: "# Key"
        case .semicolon: "; Key"
        case .quote: "\" Key"
        case .graveAccentAndTilde: "` Key"
        case .comma: ", Key"
        case .period: ". Key"
        case .slash: "/ Key"
        case .capsLock: "Caps Lock"
        case .F1: "F1"
        case .F2: "F2"
        case .F3: "F3"
        case .F4: "F4"
        case .F5: "F5"
        case .F6: "F6"
        case .F7: "F7"
        case .F8: "F8"
        case .F9: "F9"
        case .F10: "F10"
        case .F11: "F11"
        case .F12: "F12"
        case .F13: "F13"
        case .F14: "F14"
        case .F15: "F15"
        case .F16: "F16"
        case .F17: "F17"
        case .F18: "F18"
        case .F19: "F19"
        case .F20: "F20"
        case .printScreen: "Print Screen"
        case .scrollLock: "Scroll Lock"
        case .pause: "Pause"
        case .insert: "Insert"
        case .home: "Home"
        case .pageUp: "Page Up"
        case .deleteForward: "Delete"
        case .end: "End"
        case .pageDown: "Page Down"
        case .rightArrow: "Arrow Right"
        case .leftArrow: "Arrow Left"
        case .downArrow: "Arrow Down"
        case .upArrow: "Arrow Up"
        case .keypadNumLock: "Keypad Num Lock"
        case .keypadSlash: "Keypad /"
        case .keypadAsterisk: "Keypad *"
        case .keypadHyphen: "Keypad -"
        case .keypadPlus: "Keypad +"
        case .keypadEnter: "Keypad Enter"
        case .keypad1: "Keypad 1"
        case .keypad2: "Keypad 2"
        case .keypad3: "Keypad 3"
        case .keypad4: "Keypad 4"
        case .keypad5: "Keypad 5"
        case .keypad6: "Keypad 6"
        case .keypad7: "Keypad 7"
        case .keypad8: "Keypad 8"
        case .keypad9: "Keypad 9"
        case .keypad0: "Keypad 0"
        case .keypadPeriod: "Keypad ."
        case .keypadEqualSign: "Keypad ="
        case .nonUSBackslash: "\\ Key"
        case .application: "Application"
        case .power: "Power"
        case .international1: "International 1"
        case .international2: "International 2"
        case .international3: "International 3"
        case .international4: "International 4"
        case .international5: "International 5"
        case .international6: "International 6"
        case .international7: "International 7"
        case .international8: "International 8"
        case .international9: "International 9"
        case .LANG1: "LANG1"
        case .LANG2: "LANG2"
        case .LANG3: "LANG3"
        case .LANG4: "LANG4"
        case .LANG5: "LANG5"
        case .LANG6: "LANG6"
        case .LANG7: "LANG7"
        case .LANG8: "LANG8"
        case .LANG9: "LANG9"
        case .leftControl: "Left Control"
        case .leftShift: "Left Shift"
        case .leftAlt: "Left Option"
        case .leftGUI: "Left Command"
        case .rightControl: "Right Control"
        case .rightShift: "Right Shift"
        case .rightAlt: "Right Option"
        case .rightGUI: "Right Command"
        default: "Unknown \(self.rawValue)"
        }
    }
}
